exports.user = 'polymath.mailhandler@gmail.com'
exports.password = 'lckdcbhmxadzvoin'
exports.postToTest = 'tetsuro.kai87@gmail.com'
exports.postToTest2 = 'tetsulo.kai@gmail.com'
exports.postTo = 'info@polymathnyc.com'